fixes:
    - "ballerina/graphql/**/::../ballerina/"

ignore:
    - "ballerina-tests"
    - "compiler-plugin-tests"

coverage:
    precision: 2
    round: down
    range: "60...80"
    status:
        project:
            default:
                target: 80
    files: ./ballerina/target/report/graphql/coverage-report.xml,./ballerina-tests/target/report/graphql_tests/coverage-report.xml,./compiler-plugin-tests/build/reports/jacoco/test/jacocoTestReport.xml
