name: Publish Release

on:
    workflow_dispatch:
    repository_dispatch:
        types: [ stdlib-release-pipeline ]

jobs:
    publish-release:
        name: Release Package
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2

            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    distribution: 'adopt'
                    java-version: '11'

            -   name: Get Release Version
                run: echo "VERSION=$((grep -w 'version' | cut -d= -f2) < gradle.properties | rev | cut --complement -d- -f1 | rev)" >> $GITHUB_ENV

            -   name: Pre release depenency version update
                env:
                    GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
                run: |
                    echo "Version: ${VERSION}"
                    git config user.name ${{ github.actor }}
                    git config user.email ${{ secrets.GITHUB_TOKEN }}
                    git checkout -b release-${VERSION}
                    git add gradle.properties
                    git commit -m "Move dependencies to stable version" || echo "No changes to commit"

            -   name: Configure Gradle
                run: chmod +x gradlew

            -   name: Publish Package
                env:
                    GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
                    BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
                    packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                    packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                    publishUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                    publishPAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                run: |
                    ./gradlew release -Prelease.useAutomaticVersion=true
                    ./gradlew -Pversion=${VERSION} publish -x test

            -   name: GitHub Release and Release Sync PR
                env:
                    GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
                run: |
                    gh release create v$VERSION --title "module-ballerina-graphql-v$VERSION"
                    gh pr create --title "[Automated] Sync master after $VERSION release" --body "Sync master after $VERSION release"
